// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	UID      string  `json:"Uid"`
	FullName string  `json:"FullName"`
	Email    string  `json:"Email"`
	Start    string  `json:"Start"`
	End      string  `json:"End"`
	Summary  string  `json:"Summary"`
	GeoLat   float64 `json:"GeoLat"`
	GeoLon   float64 `json:"GeoLon"`
}

type Page struct {
	UserEmail string `json:"UserEmail"`
	Offset    int    `json:"Offset"`
	Limit     int    `json:"Limit"`
}
